name: weather_repo
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  weather_api:
    path: ../weather_api

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: 2.4.13
  json_serializable: 6.9.0
